#!/bin/bash
Directory_Name="assignment_dir"
Path="/c/Users/pc/Shell_scripts/assignment_dir"

if [ -d "$Path" ]; then
	echo "Directory with a Name '$Directory_Name' exists in the Location"
else 
	echo "No such directory"
fi
 


